# -*- coding: utf-8 -*-
"""LabAssignment#2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qyaVZum0JkJtA41kpQR2rF7ugbXpBd8T
"""

def checkInput(prompt, minValue, maxValue): #Function to validate input
    while True:
        try:
            value = int(input("Enter a decimal number: "))
            if minValue <= value <= maxValue:
                return value
            if value < 0:
                print(f"Please enter a positive integer")
            else:
                print(f"Please enter a value between 2 and 16.")
        except ValueError:
            print("Invalid input. Please enter an integer.")

def convertToBase(decimal, base): #Function to convert to specified base
    digits = "0123456789ABCDEF"
    result = ""
    while decimal > 0:
        remainder = decimal % base
        result = digits[remainder] + result
        decimal //= base
    return result

decimalNumber = checkInput("Enter a decimal number: ", 0, float('inf'))
base = checkInput("Enter the base (between 2 and 16): ", 2, 16)

baseValue = convertToBase(decimalNumber, base)
print(f"The equivalent base-{base} value of decimal {decimalNumber} is: {baseValue}")